-- MySQL Script generated by MySQL Workbench
-- 05/08/16 15:26:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cijenanamirnice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cijenanamirnice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cijenanamirnice` (
  `nazivNamirnice` VARCHAR(45) NOT NULL,
  `cijena` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`nazivNamirnice`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`namirnica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`namirnica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`namirnica` (
  `idNamirnica` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `kolicina` INT(11) NOT NULL,
  `cijena` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`idNamirnica`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
